<?php
  lazyblocks()->add_block( array(
    'id' => 43,
    'title' => 'Full Section',
    'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
</svg>',
    'keywords' => array(
    ),
    'slug' => 'lazyblock/full-section',
    'description' => '',
    'category' => 'text',
    'category_label' => 'text',
    'supports' => array(
        'customClassName' => true,
        'anchor' => false,
        'html' => false,
        'multiple' => true,
        'inserter' => true,
        'reusable' => true,
        'lock' => true,
        'align' => array(
            0 => 'wide',
            1 => 'full',
        ),
    ),
    'ghostkit' => array(
        'supports' => array(
            'spacings' => false,
            'display' => false,
            'scrollReveal' => false,
            'frame' => false,
            'customCSS' => false,
        ),
    ),
    'controls' => array(
        'control_c4eb674d9e' => array(
            'type' => 'text',
            'name' => 'heading',
            'default' => '',
            'label' => 'Heading',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_005af04c3e' => array(
            'type' => 'repeater',
            'name' => 'sections',
            'default' => '',
            'label' => 'Sections',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'rows_min' => '',
            'rows_max' => '',
            'rows_label' => '',
            'rows_add_button_label' => '',
            'rows_collapsible' => 'true',
            'rows_collapsed' => 'true',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_802b484abb' => array(
            'type' => 'text',
            'name' => 'title',
            'default' => '',
            'label' => 'Title',
            'help' => '',
            'child_of' => 'control_005af04c3e',
            'placement' => 'content',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_a1cb9a4c17' => array(
            'type' => 'text',
            'name' => 'description',
            'default' => '',
            'label' => 'Description',
            'help' => '',
            'child_of' => 'control_005af04c3e',
            'placement' => 'content',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_7128e9446a' => array(
            'type' => 'select',
            'name' => 'background',
            'default' => 'bg-light-taupe',
            'label' => 'Background',
            'help' => '',
            'child_of' => 'control_005af04c3e',
            'placement' => 'content',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'choices' => array(
                array(
                    'label' => 'Light Taupe',
                    'value' => 'bg-light-taupe',
                ),
                array(
                    'label' => 'Sage Green',
                    'value' => 'bg-sage-green',
                ),
                array(
                    'label' => 'Terracotta',
                    'value' => 'bg-terracotta',
                ),
                array(
                    'label' => 'Neutral Grey',
                    'value' => 'bg-neutral-grey',
                ),
            ),
            'allow_null' => 'false',
            'multiple' => 'false',
            'output_format' => '',
            'placeholder' => '',
            'characters_limit' => '',
        ),
    ),
    'code' => array(
        'output_method' => 'template',
        'editor_html' => '',
        'editor_callback' => '',
        'editor_css' => '',
        'frontend_html' => '',
        'frontend_callback' => '',
        'frontend_css' => '',
        'show_preview' => 'always',
        'single_output' => false,
    ),
    'styles' => array(
        array(
            'name' => 'Test',
            'label' => 'Testing',
        ),
    ),
    'condition' => array(
    ),
) );