<?php
 lazyblocks()->add_block( array(
    'id' => 53,
    'title' => 'Portfolio',
    'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
</svg>',
    'keywords' => array(
    ),
    'slug' => 'lazyblock/portfolio',
    'description' => '',
    'category' => 'text',
    'category_label' => 'text',
    'supports' => array(
        'customClassName' => true,
        'anchor' => false,
        'html' => false,
        'multiple' => true,
        'inserter' => true,
        'reusable' => true,
        'lock' => true,
        'align' => array(
            0 => 'wide',
            1 => 'full',
        ),
    ),
    'ghostkit' => array(
        'supports' => array(
            'spacings' => false,
            'display' => false,
            'scrollReveal' => false,
            'frame' => false,
            'customCSS' => false,
        ),
    ),
    'controls' => array(
        'control_c4b8cd4e8f' => array(
            'type' => 'text',
            'name' => 'heading',
            'default' => '',
            'label' => 'Heading',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_31bb0a4579' => array(
            'type' => 'textarea',
            'name' => 'description',
            'default' => '',
            'label' => 'Description',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_ca7a264b71' => array(
            'type' => 'url',
            'name' => 'button',
            'default' => '',
            'label' => 'Button',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_91ca434c8c' => array(
            'type' => 'image',
            'name' => 'image-main',
            'default' => '',
            'label' => 'Image Main',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'insert_from_url' => 'false',
            'preview_size' => 'medium',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_aa588c45df' => array(
            'type' => 'image',
            'name' => 'image-second',
            'default' => '',
            'label' => 'Image Second',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'insert_from_url' => 'false',
            'preview_size' => 'medium',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_18e8a14315' => array(
            'type' => 'image',
            'name' => 'image-third',
            'default' => '',
            'label' => 'Image Third',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'required' => 'false',
            'translate' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'insert_from_url' => 'false',
            'preview_size' => 'medium',
            'placeholder' => '',
            'characters_limit' => '',
        ),
    ),
    'code' => array(
        'output_method' => 'template',
        'editor_html' => '',
        'editor_callback' => '',
        'editor_css' => '',
        'frontend_html' => '',
        'frontend_callback' => '',
        'frontend_css' => '',
        'show_preview' => 'always',
        'single_output' => false,
    ),
    'styles' => array(
    ),
    'condition' => array(
    ),
) );