<?php
lazyblocks()->add_block(
    array(
        'id' => 35,
        'title' => 'Services',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M7 5h2V3H7v2zm0 8h2v-2H7v2zm0 8h2v-2H7v2zm4-4h2v-2h-2v2zm0 4h2v-2h-2v2zm-8 0h2v-2H3v2zm0-4h2v-2H3v2zm0-4h2v-2H3v2zm0-4h2V7H3v2zm0-4h2V3H3v2zm8 8h2v-2h-2v2zm8 4h2v-2h-2v2zm0-4h2v-2h-2v2zm0 8h2v-2h-2v2zm0-12h2V7h-2v2zm-8 0h2V7h-2v2zm8-6v2h2V3h-2zm-8 2h2V3h-2v2zm4 16h2v-2h-2v2zm0-8h2v-2h-2v2zm0-8h2V3h-2v2z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/services',
        'description' => '',
        'category' => 'theme',
        'category_label' => 'theme',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_08a9264481' => array(
                'type' => 'image',
                'name' => 'image',
                'default' => '',
                'label' => 'Image',
                'help' => '',
                'child_of' => '',
                'placement' => 'both',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'insert_from_url' => 'false',
                'preview_size' => 'medium',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6a28334275' => array(
                'type' => 'text',
                'name' => 'heading',
                'default' => '',
                'label' => 'Heading',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_9dd9ad48f4' => array(
                'type' => 'text',
                'name' => 'subheading',
                'default' => '',
                'label' => 'Subheading',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_8f1abb447f' => array(
                'type' => 'repeater',
                'name' => 'services',
                'default' => '',
                'label' => 'Services',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_43086a445c' => array(
                'type' => 'image',
                'name' => 'image',
                'default' => '',
                'label' => 'Image',
                'help' => '',
                'child_of' => 'control_8f1abb447f',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'insert_from_url' => 'false',
                'preview_size' => 'medium',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_7039b14c2c' => array(
                'type' => 'text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => 'control_8f1abb447f',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_24b9964387' => array(
                'type' => 'textarea',
                'name' => 'description',
                'default' => '',
                'label' => 'Description',
                'help' => '',
                'child_of' => 'control_8f1abb447f',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'always',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ));